version: '3'

services:
  lychee:
    image: lycheeorg/lychee
    container_name: lychee
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.local-lychee.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.local-lychee.entrypoints=websecure"
      - "traefik.http.routers.local-lychee.tls=true"
      - "traefik.http.services.local-lychee.loadbalancer.server.port=80"
    depends_on:
      majeskjuel:
        condition: service_started
    volumes:
      - ./lychee/conf:/conf
      - ./lychee/uploads:/uploads
      - ./lychee/sym:/sym
    networks:
      - backend
      - traefik-public
    environment:
      # PHP timezone e.g. PHP_TZ=America/New_York
      - PHP_TZ=UTC
      - TIMEZONE=UTC
      - APP_FORCE_HTTPS=true
      - APP_URL=https://${DOMAIN_NAME}
      - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST}
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - STARTUP_DELAY=10
    restart: unless-stopped
  
  majeskjuel:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    volumes:
      - ./mariadb/datadir:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.local-lychee-adminer.rule=Host(`adminer-${DOMAIN_NAME}`)"
      - "traefik.http.routers.local-lychee-adminer.entrypoints=websecure"
      - "traefik.http.routers.local-lychee-adminer.tls=true"
      - "traefik.http.services.local-lychee-adminer.loadbalancer.server.port=8080"
    environment:
      - ADMINER_DEFAULT_SERVER=${DB_HOST}
    restart: always
    networks:
      - backend
      - traefik-public

networks:
  backend:
  traefik-public:
    external: true
